### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'hortusfox.users' doesn't exist

### ISSUE THREAD

**Issue by MarcelBruckner** [danielbrendel/hortusfox-web#68] opened 2024-01-12 14:51 UTC
At first: Thank you for your efforts to create and share this project.
I really appreciate what you have build and really like to use it.
Keep up the great work!

---

### Expected Behavior
I can login to hortusfox-web via the web UI.

### Current Behavior
The web UI shows the error:
```SQLSTATE[42S02]: Base table or view not found: 1146 Table 'hortusfox.users' doesn't exist```

### Possible Solution
The `app` container has to wait for the mariaDB database in the `db` container to be fully started.
The `depends_on` setting in the `docker-compose.yml` only waits for the `db` container to be up and running, but not for the mariaDB to be in a usable state

### Steps to Reproduce
1. Run hortusfox-web via [docker-compose](https://github.com/danielbrendel/hortusfox-web?tab=readme-ov-file#docker-and-docker-compose)
2. Open the web UI
3. Login with the admin user

### Context (Environment)
```shell
[+] Running 3/2
 ✔ Network hortusfox-web_default  Created                                                         0.1s
 ✔ Container hortusfox-web-db-1   Created                                                         0.0s
 ✔ Container hortusfox-web-app-1  Created                                                         0.0s
Attaching to hortusfox-web-app-1, hortusfox-web-db-1
hortusfox-web-db-1   | 2024-01-12 14:40:41+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:11.2.2+maria~ubu2204 started.
hortusfox-web-db-1   | 2024-01-12 14:40:41+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
hortusfox-web-db-1   | 2024-01-12 14:40:41+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:11.2.2+maria~ubu2204 started.
hortusfox-web-app-1  | Running database migrations...
hortusfox-web-app-1  |
hortusfox-web-app-1  | Fatal error: Uncaught PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/www/html/vendor/danielbrendel/asatru-php-framework/src/database.php:1178
hortusfox-web-app-1  | Stack trace:
hortusfox-web-app-1  | #0 /var/www/html/vendor/danielbrendel/asatru-php-framework/src/database.php(1178): PDO->__construct('mysql:host=db;p...', 'root', Object(SensitiveParameterValue))
hortusfox-web-app-1  | #1 /var/www/html/asatru(33): require_once('/var/www/html/v...')
hortusfox-web-app-1  | #2 {main}
hortusfox-web-app-1  |   thrown in /var/www/html/vendor/danielbrendel/asatru-php-framework/src/database.php on line 1178
hortusfox-web-app-1  | ERROR 2002 (HY000): Can't connect to MySQL server on 'db' (115)
hortusfox-web-app-1  | Admin user (admin@example.com) does not exist. Creating...
hortusfox-web-db-1   | 2024-01-12 14:40:42+00:00 [Note] [Entrypoint]: MariaDB upgrade not required
hortusfox-web-app-1  | ERROR 2002 (HY000): Can't connect to MySQL server on 'db' (115)
hortusfox-web-app-1  | Admin user created. Username: admin@example.com, Password: f2UjCuHJsvIxsl4m
hortusfox-web-db-1   | 2024-01-12 14:40:42 0 [Note] Starting MariaDB 11.2.2-MariaDB-1:11.2.2+maria~ubu2204 source revision 929532a9426d085111c24c63de9c23cc54382259 as process 1
hortusfox-web-db-1   | 2024-01-12 14:40:42 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
hortusfox-web-db-1   | 2024-01-12 14:40:42 0 [Note] InnoDB: Number of transaction pools: 1
hortusfox-web-db-1   | 2024-01-12 14:40:42 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
hortusfox-web-db-1   | 2024-01-12 14:40:42 0 [Note] mariadbd: O_TMPFILE is not supported on /tmp (disabling future attempts)
hortusfox-web-db-1   | 2024-01-12 14:40:42 0 [Note] InnoDB: Using liburing
hortusfox-web-db-1   | 2024-01-12 14:40:42 0 [Note] InnoDB: Initializing buffer pool, total size = 128.000MiB, chunk size = 2.000MiB
hortusfox-web-db-1   | 2024-01-12 14:40:42 0 [Note] InnoDB: Completed initialization of buffer pool
hortusfox-web-db-1   | 2024-01-12 14:40:42 0 [Note] InnoDB: File system buffers for log disabled (block size=512 bytes)
hortusfox-web-db-1   | 2024-01-12 14:40:42 0 [Note] InnoDB: End of log at LSN=47763
hortusfox-web-app-1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.29.0.3. Set the 'ServerName' directive globally to suppress this message
hortusfox-web-db-1   | 2024-01-12 14:40:42 0 [Note] InnoDB: Opened 3 undo tablespaces
hortusfox-web-db-1   | 2024-01-12 14:40:42 0 [Note] InnoDB: 128 rollback segments in 3 undo tablespaces are active.
hortusfox-web-db-1   | 2024-01-12 14:40:42 0 [Note] InnoDB: Removed temporary tablespace data file: "./ibtmp1"
hortusfox-web-db-1   | 2024-01-12 14:40:42 0 [Note] InnoDB: Setting file './ibtmp1' size to 12.000MiB. Physically writing the file full; Please wait ...
hortusfox-web-db-1   | 2024-01-12 14:40:42 0 [Note] InnoDB: File './ibtmp1' size is now 12.000MiB.
hortusfox-web-app-1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.29.0.3. Set the 'ServerName' directive globally to suppress this message
hortusfox-web-db-1   | 2024-01-12 14:40:42 0 [Note] InnoDB: log sequence number 47763; transaction id 14
hortusfox-web-db-1   | 2024-01-12 14:40:42 0 [Note] Plugin 'FEEDBACK' is disabled.
hortusfox-web-db-1   | 2024-01-12 14:40:42 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
hortusfox-web-db-1   | 2024-01-12 14:40:42 0 [Note] Plugin 'wsrep-provider' is disabled.
hortusfox-web-db-1   | 2024-01-12 14:40:42 0 [Note] Recovering after a crash using tc.log
hortusfox-web-db-1   | 2024-01-12 14:40:42 0 [Note] Starting table crash recovery...
hortusfox-web-db-1   | 2024-01-12 14:40:42 0 [Note] Crash table recovery finished.
hortusfox-web-db-1   | 2024-01-12 14:40:42 0 [Note] InnoDB: Buffer pool(s) load completed at 240112 14:40:42
hortusfox-web-db-1   | 2024-01-12 14:40:42 0 [Note] Server socket created on IP: '0.0.0.0'.
hortusfox-web-db-1   | 2024-01-12 14:40:42 0 [Note] Server socket created on IP: '::'.
hortusfox-web-db-1   | 2024-01-12 14:40:42 0 [Note] mariadbd: Event Scheduler: Loaded 0 events
hortusfox-web-db-1   | 2024-01-12 14:40:42 0 [Note] mariadbd: ready for connections.
hortusfox-web-db-1   | Version: '11.2.2-MariaDB-1:11.2.2+maria~ubu2204'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
hortusfox-web-app-1  | [Fri Jan 12 14:40:42.198356 2024] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.54 (Debian) PHP/8.2.0 configured -- resuming normal operations
hortusfox-web-app-1  | [Fri Jan 12 14:40:42.198401 2024] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```

The lines `hortusfox-web-app-1  | ERROR 2002 (HY000): Can't connect to MySQL server on 'db' (115)` show, that the mariaDB database is not ready for the app to connect.

### Possible Implementation
A quick workaround that I'm using is to add a `sleep 10` to the `docker-entrypoint.sh`, e.g.:
```shell
...

### This is the additional wait for the database
sleep 10

# Configure PHP error reporting
configure_php_error_reporting

# Create .env configuration file
create_environment_file

# Run database migrations
echo "Running database migrations..."
php asatru migrate:fresh

...
```

A better solution would be to have a polling until the mariaDB database is ready, and only then start the app.

**Comment by InputObject2** [comment] 2024-01-12 15:11
We could add something that polls the DB instead of just sleeping for 10s. In some cases it might take much longer than 10s to startup.

**Comment by InputObject2** [comment] 2024-01-12 15:25
@MarcelBruckner I have a hard time replicating this with my setup because mariadb starts up too fast... Can you try out this fix version I pushed and let me know if it works for you?

docker.io/inputobject2/hortusfox-web:1.6-dbwait

**Comment by danielbrendel** [comment] 2024-01-12 16:12
Hi, thank you for your appreciation! Glad you like the product.

I can reproduce this, because this always happens in my environment (slow computer).

Here are some different solutions we can investigate: https://stackoverflow.com/questions/25503412/how-do-i-know-when-my-docker-mysql-container-is-up-and-mysql-is-ready-for-taking

At least checking until db connections are accepted is required. Also we could make a test query to see if the db does actually answer queries. Could be just something like _SELECT VERSION() AS version_ to validate that the db does accept and respond to queries. This combined in a loop in the docker shell script should suffice I guess.

**Comment by danielbrendel** [comment] 2024-01-13 01:45
#73 should have solved the issue. If you can confirm this I can close this issue afterwards. For me this works fine now.

**Comment by danielbrendel** [comment] 2024-01-19 23:06
Closing this here, because this issue seems to be resolved.

**Closed by danielbrendel** 2024-01-19 23:06 UTC
Labels: bug, improvement

**Comment by circle3451** [comment] 2024-02-25 18:26
Im getting the same error using the docker compose example

**Comment by janaxhell** [comment] 2024-03-31 09:55
Hi, same here, just deployed the docker-compose and I'm getting this output on dashboard page:

```
500
Internal Server Error
Exception at /var/www/html/vendor/danielbrendel/asatru-php-framework/src/database.php:643
Reported error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'hortusfox.AppModel' doesn't exist
[Refresh](javascript:void(0);)
Stack trace:
#8 /var/www/html/vendor/danielbrendel/asatru-php-framework/src/database.php(643): PDOStatement::execute
#7 /var/www/html/app/models/AppModel.php(17): Asatru\Database\Model::raw ( 'SELECT * FROM `AppModel` WHERE id = ?' , array )
#6 /var/www/html/app/helper/AppHelper.php(10): AppModel::query ( 'smtp_fromname' )
#5 /var/www/html/app/helper/AppHelper.php(23): app ( 'smtp_fromname' )
#4 /var/www/html/app/controller/_base.php(26): app_mail_config
#3 /var/www/html/app/controller/user.php(16): BaseController::__construct ( 'layout' )
#2 /var/www/html/vendor/danielbrendel/asatru-php-framework/src/controller.php(584): UserController::__construct
#1 /var/www/html/vendor/danielbrendel/asatru-php-framework/src/bootstrap.php(123): Asatru\Controller\ControllerHandler::parse ( '/profile' )
#0 /var/www/html/public/index.php(25): require_once ( '/var/www/html/vendor/danielbrendel/asatru-php-framework/src/bootstrap.php' )
```
hortusfox-app log shows:

```
Database is available.
Running full database migrations...
CLI tool is only available in debug mode
ERROR 1146 (42S02) at line 1: Table 'hortusfox.AppModel' doesn't exist
App settings profile does not exist. Creating...
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' , , , , , , '', , '', , 'Hortusfox', 'XXXXXXXXXXX', 'XXXXXXXXXX...' at line 1
App settings profile created.
ERROR 1146 (42S02) at line 1: Table 'hortusfox.users' doesn't exist
Admin user (XXXXXXXXXXX) does not exist. Creating...
ERROR 1146 (42S02) at line 1: Table 'hortusfox.users' doesn't exist
Admin user created. Username: XXXXXXXXX. Password: **HIDDEN**
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.16.0.13. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.16.0.13. Set the 'ServerName' directive globally to suppress this message
[Sun Mar 31 09:25:42.391226 2024] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.54 (Debian) PHP/8.2.0 configured -- resuming normal operations
[Sun Mar 31 09:25:42.391271 2024] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
192.168.1.21 - - [31/Mar/2024:09:25:46 +0000] "GET /profile HTTP/1.1" 200 1994 "http://192.168.1.164:6452/profile" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
192.168.1.21 - - [31/Mar/2024:09:25:47 +0000] "GET /img/pattern.jpg HTTP/1.1" 200 60758 "http://192.168.1.164:6452/profile" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"

```
