### ISSUE TITLE
Feature Request : Notes or Mini Wiki

### ISSUE THREAD

**Issue by kaleben0** [danielbrendel/hortusfox-web#296] opened 2024-11-02 02:15 UTC
**Description of your request**
Add a section, separate from the rest, were you can store information, like notes and links to articles. 
Maybe you do a bookmark page, were you could store links to articles, descriptions and notes. 
The wysiwyg editor or a markdown editor are widely used.  
You could also have the option of creating a link to existing plants or a link to the note in the plant status page. 

Example : I create a "note" about how to harvest basil, then I can go into my basil plant's entry and bring up a list of existing "notes" and link that note to the plant. Then in the future, I can go into the plant and have the link to my notes right there. 

**Describe alternatives you've considered**
Currently, I am using Bookstack to store gardening information. 
It would be cool to have everything in one place.

**Comment by danielbrendel** [comment] 2024-11-03 14:03
Hi, thanks for your request. This is a duplicate of #283 and will be worked on in that particular issue.

**Closed by danielbrendel** 2024-11-03 14:03 UTC
Labels: duplicate, enhancement, improvement

**Comment by kaleben0** [comment] 2024-11-03 21:23
Ah, didn't see the other request. Thank You!
