### ISSUE TITLE
Allow photos to be uploaded directly from android to Hortusfox

### ISSUE THREAD

**Issue by dghoti** [danielbrendel/hortusfox-web#308] opened 2024-11-18 19:09 UTC
**Describe the bug**
On android 13 - I can directly upload a picture from my phone (bypassing the gallery on my phone).
Since upgrade to android 14, this no longer works.
There is a fix described here:
https://stackoverflow.com/questions/77873768/android-14-photo-picker-camera-tile-removed-from-google-chrome

Typical Android13:
![image](https://github.com/user-attachments/assets/6bac5993-0df7-448a-9ea3-ba2ea109aac3)

Typical Android14, notice lack of camera option:
![image](https://github.com/user-attachments/assets/f770bd41-7b1a-4676-9884-a83b490cc1d9)

**Comment by danielbrendel** [comment] 2024-11-22 14:51
Hi, actually this is not a bug within HortusFox, but rather a 1-year old
bug within Google Chrome and it does work with other browsers on Android 14
as expected.
This issue has been raised on the issue tracker at Google:
https://issuetracker.google.com/issues/317289301?pli=1
Sadly they have remained very unresponsive so far.
A workaround can be a JavaScript code that checks for all input[type=file]
elements and checks if it only accepts images, then it can add another
random attribute in order to circumvent chromes erroneous behaviour. I can
provide that later.
Unfortunately this is the only solution right now, because using your
mentioned workaround can break the behaviour in other browsers which would
not be fair.
Hope this helps so far.

**Comment by dghoti** [comment] 2024-11-23 14:38
I appreciate your position, thank you

**Comment by dghoti** [comment] 2024-11-25 15:46
Hi,,Have tried it again, using firefox as you suggest this is an issue with chrome only.
I can upload plant pictures, but not photos for identification

so it seems this is still present in firefox as well as chrome on android 14

Does nobypass gallery in firefox (allow direct photo upload):

![Screenshot_20241125-150543](https://github.com/user-attachments/assets/64335044-60ba-412f-a192-216a7a989903)

Does bypass gallery (upload direct from camera) in firefox:
![Screenshot_20241125-150615](https://github.com/user-attachments/assets/ad8795b8-9f07-43d8-838b-b91d90c5aeab)


so thanks - I can workaround one isssue, but uploading the plant picture for automatic identification, still needs the photo to be taken (and added to the gallery first). Ideally this identification step would be the preferrred one to skip the gallery - but this "omission" seems to present itself in chrome or firefox

**Comment by danielbrendel** [comment] 2024-11-25 21:50
Hi, yeah, that's right, this is a bug. The reason is that the
`accept="image/*"` is missing for the identification file input. I'll add
it for the next release. Thanks for reporting!

**Comment by danielbrendel** [comment] 2024-12-03 14:51
Closing this for now, keeping an eye on the issue tracker.

**Closed by danielbrendel** 2024-12-03 14:51 UTC
Labels: bug
