### ISSUE TITLE
Bulk update

### ISSUE THREAD

**Issue by kenske** [danielbrendel/hortusfox-web#268] opened 2024-09-12 03:05 UTC
**Description of your request**
Update custom attributes for multiple plants in one request

**Describe the solution you'd like**
Just like it's possible to update several plants simultaneously for certain actions (fertilizing, watering, etc), it would be great to be able to do this for custom attributes (for example: fungus treatment applied, pesticide added, etc) .

**Describe alternatives you've considered**
The current alternative is to do it manually for each plant.

**Additional context**
N/A

**Comment by kenske** [comment] 2024-09-13 00:41
Sorry, yes, "fertilized" was a bad example. I meant to reference custom attributes. For example, I have several plants that require me to apply a fungus treatment. I'd like to do that for several plants in a single action.

I'll update the original description.

**Comment by danielbrendel** [comment] 2024-09-15 18:50
Ah, okay. I'll see how this can be implemented in one of the next versions.

**Comment by danielbrendel** [comment] 2024-09-23 00:05
Duplicate of #263

**Closed by danielbrendel** 2024-09-23 00:05 UTC
Labels: duplicate
