### ISSUE TITLE
Mysql Error from using Apostrophe in name. 

### ISSUE THREAD

**Issue by tumeden** [danielbrendel/hortusfox-web#237] opened 2024-07-13 20:20 UTC
**Describe the bug**
Mysql error caused from using apostrophe in name.

**To Reproduce**
Add a name including an apostrophe to an inventory item name
example:  **Grampy's Soil**

**Expected behavior**
For you to be able to use an apostrophe

**Screenshots**
![image](https://github.com/user-attachments/assets/9ff5d882-723b-4768-a1ff-1853326fce31)

**More details**
An string or a sql statement with an apostrophe becomes a unclosed string because of the presence of that single 'quote'

**Software:**
HortusFox v3.2
PHP Version: 8.3.0
MySQL Version: 9.0.0

**Comment by danielbrendel** [comment] 2024-07-15 10:30
Works flawlessly with MariaDB. Trying to reproduce with MySQL.

**Comment by danielbrendel** [comment] 2024-07-15 10:50
@tumeden I see now what's happening. The problem is that when you tried to add the item to your inventory using the group identified via the token `300`, it appears that the group item does not exist. That's why you get that message. The message `Invalid group token: 300` indicates that there is no such group with the given token. It might be that someone deleted the group before you tried to add an inventory item while your page was not refreshed, so the group was still in list.

**Comment by danielbrendel** [comment] 2024-07-22 22:12
Resolved via 56abc5f3da0a302c2c4ff67dc9c5f1c6941b1b58

**Closed by danielbrendel** 2024-07-22 22:12 UTC
Labels: bug
